---
galaxy_info:
  role_name: cockpit
  description: Installs Cockpit and net-tools on a target system.
  author: MalavikaSelvan
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - all

